version: '3'
services:
  app:
    container_name: p2p_isi
    build: 
        context: .
        dockerfile: Dockerfile
    image: psp_isi_app
    init: true
    tty: true
    stdin_open: true # This needs to be removed in production
    privileged: true # This needs to be removed in production
    volumes:
      - ../:/workspace
    ports:
      - 7777:7777
    restart: unless-stopped
